export const LOCALSTORAGE = "hitta-store";
export const CAROUSEL_SWITCH_ITEM = "CAROUSEL/SWITCH_ITEM";
export const CART_ADD_ITEM = "CART/ADD_ITEM";
export const CART_REMOVE_ITEM = "CART/REMOVE_ITEM";
export const ADD_ITEMS = "ADD_ITEMS";
export const CART_CHANGE_OPTION = "CART/CHANGE_OPTION"
export const CART_CLEAR_CART = "CART/CLEAR_CART"

export const APP_SWITCH_CURRENCY = "APP/SWITCH_CURRENCY";
export const APP_SWITCH_LANGUAGE = "APP/SWITCH_LANGUAGE";
export const LANGUAGE_US = "US";
export const LANGUAGE_RUS = "RU";
export const CURRENCY_RUBLE = "RUB";
export const CURRENCY_DOLLAR = "USD";

export const PAYMENT_CREATE_PAYMENT_START = "PAYMENT/CREATE_PAYMENT_START";
export const PAYMENT_CREATE_PAYMENT_SUCCESS = "PAYMENT/CREATE_PAYMENT_SUCCESS";
export const PAYMENT_CREATE_PAYMENT_ERROR = "PAYMENT/CREATE_PAYMENT_ERROR";
export const PAYMENT_CREATE_PAYMENT_VALIDATION_ERRORS = "PAYMENT/CREATE_PAYMENT_VALIDATION_ERRORS"
export const PAYMENT_STORE_PAYMENT = "PAYMENT/STORE_PAYMENT";

export const PAYMENT_CHECK_PAYMENT_STATUS_START = "PAYMENT/CHECK_PAYMENT_STATUS_START";
export const PAYMENT_CHECK_PAYMENT_STATUS_SUCCESS = "PAYMENT/CHECK_PAYMENT_STATUS_SUCCESS";
export const PAYMENT_CHECK_PAYMENT_STATUS_ERROR = "PAYMENT/CHECK_PAYMENT_STATUS_ERROR";